language: ruby
rvm: 2.1.2
cache: bundler
branches:
    only:
        - master
script:
    - bundle exec middleman build
after_success:
    - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && bundle exec middleman deploy >/dev/null 2>&1'
env:
    global:
        - GIT_COMMITTER_NAME='whoami'
        - GIT_COMMITTER_EMAIL='whoami@travis'
        - GIT_AUTHOR_NAME='whoami'
        - GIT_AUTHOR_EMAIL='whoami@travis'
        - secure: "LoWFENS4tKAENxgozkewW0mMeWnqos+3l7GZH/cnN/PlZXhchRspruAgkof2vwJgXX63png1BoTssinEtHq4oNli4x0J1paKXW6W2+W2CPoSnlHNz4ktS0pHwZr8mg2FrRGih3grS0drjQ8J4IAuEQv7OkAVLPAzD4A6DSm2TmI="
